blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView

# http://localhost:8000 요청이 들어왔을 때 우리 전체 project의 홈페이지로
# 이동시킬 거예요!
# Django는 elegant URL을 지원해요!
# 정규표현식(regular expression)
# 시작 => ^, 끝 => $
# [0-9] : 1글자를 지칭
# {3,5}: 3번 반복
# [0-9]{4}
# r(raw)은 escape 문자를 한번 더 사용하지 않도록 처리
# r"^[0-9]{1,3}$"
# r"^010[1-9]\d{6,7}$"

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name = 'index.html'), name = "home"),
    path('admin/',admin.site.urls),
    path('posts/', include('posts.urls'))
]

posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('list/', views.p_list, name = 'list'),
    path('create/', views.p_create, name = 'create'),
    path('<int:post_id>/update', views.p_update, name = 'update'),
    path('<int:post_id>/delete', views.p_delete, name = 'delete'),
    path('<int:post_id>/', views.p_detail, name = 'p_detail'),
    path('<int:post_id>/comment/', views.add_comment_to_post, name = 'add_comment_to_post'),
    path('<int:comment_id>/c_update', views.c_update, name = 'update_comment'),
    path('<int:comment_id>/c_delete', views.c_delete, name = 'delete_comment'),
    path('<int:comment_id>/c_detail', views.c_detail, name = 'c_detail')

]

posts/models.py
from django.db import models

class Post(models.Model):
    contents = models.TextField('글내용', max_length = 1000)
    author = models.CharField('작성자', max_length = 20)

    def __str__(self):
        return self.contents

class Comment(models.Model):
    contents_comment = models.TextField('댓글내용', max_length = 1000)
    author_comment = models.CharField('댓글 작성자', max_length = 20)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.contents_comment

posts/forms.py
# forms.py

from django import forms
from posts.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['author', 'contents']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author_comment', 'contents_comment']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from posts.models import Post, Comment
from posts.forms import PostForm, CommentForm


def p_list(request):
    my_list = Post.objects.all().order_by('-id')
    context = {'posts': my_list}
    return render(request, 'list.html', context)

def p_create(request):
    # POST 방식으로 호출될 때
    if request.method == 'POST':
        post_form = PostForm(request.POST)

        if post_form.is_valid():
            post_form.save()
            return redirect('posts:list')
        # GET 방식으로 호출될 때
    else:
        post_form = PostForm()

    return render(request, 'create.html', {'post_form': post_form})

def p_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()

    return redirect('posts:list')

def p_update(request, post_id):

    post = get_object_or_404(Post, pk=post_id)

    # POST 방식으로 호출될 떄
    if request.method == 'POST':
        post_form = PostForm(request.POST, instance=post)

        if post_form.is_valid():
            post_form.save()
            return redirect('posts:list')

    # GET 방식으로 호출될 때
    else:
        post_form = PostForm(instance=post)

    return render(request, 'create.html', {'post_form': post_form})

def p_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'p_detail.html', {'post':post})

def add_comment_to_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        comment = Comment(post=post)
        comment_form = CommentForm(request.POST, instance=comment)
        if comment_form.is_valid():
            comment_form.save()
            path = '/posts/{}/'.format(post_id)
            return redirect(path)

    else:
        comment_form = CommentForm()
        return render(request, 'add_comment_to_post.html', {'comment_form':comment_form})

def c_delete(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    post = Post.objects.get(id=comment.post_id)

    return render(request, 'p_detail.html', {'post':post})

def c_update(request, comment_id):

    comment = get_object_or_404(Comment, pk=comment_id)
    post = Post.objects.get(id=comment.post_id)

    # POST 방식으로 호출될 떄
    if request.method == 'POST':
        comment_form = CommentForm(request.POST, instance=comment)

        if comment_form.is_valid():
            comment_form.save()
            return render(request, 'p_detail.html', {'post':post})

    # GET 방식으로 호출될 때
    else:
        comment_form = CommentForm(instance=comment)

    return render(request, 'c_update.html', {'comment_form': comment_form})

def c_detail(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    return render(request, 'c_detail.html', {'comment':comment})

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
</head>
<body>
    {% block container %}
    {% endblock %}
</body>
</html>

blog/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Blog System</title>

    <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="/static/css/cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">My Blog</h3>
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">Welcome To My Blog</h1>
    <p class="lead">powered by bootstrap</p>
    <p class="lead">
      <a href="/posts/list/" class="btn btn-lg btn-secondary">Enter BBS</a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
  </footer>
</div>
</body>
</html>

posts/templates/add_comment_to_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block container %}
    <div class = "container">
        <h1>새댓글 작성</h1>
        <form method = "post">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <button type = "submit" class = "btn btn-primary">등록</button>
        </form>
    </div>
{% endblock %}

posts/templates/c_detail.html
{% extends 'base.html' %}
{% block container %}

<div class = "container">
       <h1>상세보기</h1>
       <div class = "m-1"></div>

       <table class = "table table-hover">
           <thead class = "thead-dark">
           <tr>

               <th scope = "col">글 내용</th>
               <th scope = "col">작성자</th>


           </tr>
           </thead>
           <tbody>

               <tr>

                   <td>{{ comment.contents_comment }}</td>
                   <td>{{ comment.author_comment }}</td>
               </tr>

           </tbody>
       </table>
    {% endblock %}

posts/templates/c_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block container %}
    <div class = "container">
        <h1>새글 작성</h1>
        <form method = "post">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <button type = "submit" class = "btn btn-primary">등록</button>
        </form>
    </div>
{% endblock %}

posts/templates/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block container %}
    <div class = "container">
        <h1>새글 작성</h1>
        <form method = "post">
            {% csrf_token %}
            {% bootstrap_form post_form %}
            <button type = "submit" class = "btn btn-primary">등록</button>
        </form>
    </div>
{% endblock %}

posts/templates/list.html
{% extends 'base.html' %}
{% block container %}
   <script src = "/static/js/posts.js"></script>
   <div class = "container">
       <h1>Bulletin Board System(BBS)</h1>
       <button class = "btn btn-primary"
               onclick = "new_post()">새글 작성</button>
       <div class = "m-1"></div>

       <table class = "table table-hover">
           <thead class = "thead-dark">
           <tr>
               <th scope = "col">#</th>
               <th scope = "col">제목</th>
               <th scope = "col">작성자</th>


           </tr>
           </thead>
           <tbody>
               {% for post in posts %}
               <tr>
                   <th scope = "row">{{ post.id }}</th>
                   <td><a href="/posts/{{ post.id }}">{{ post.contents }}</a></td>
                   <td>{{ post.author }}</td>

               </tr>
               {% endfor %}
           </tbody>
       </table>
   </div>
{% endblock %}

posts/templates/p_detail.html
{% extends 'base.html' %}
{% block container %}

<div class = "container">
       <h1>상세보기</h1>
       <div class = "m-1"></div>

       <table class = "table table-hover">
           <thead class = "thead-dark">
           <tr>

               <th scope = "col">글 내용</th>
               <th scope = "col">작성자</th>


           </tr>
           </thead>
           <tbody>

               <tr>

                   <td>{{ post.contents }}</td>
                   <td>{{ post.author }}</td>
               </tr>

           </tbody>
       </table>
       <a class = "btn btn-primary" href = "{% url 'posts:update' post.id %}" class = "btn btn-warning">수정</a>
       <a class = "btn btn-primary" href= "{% url 'posts:delete' post.id %}" class = "btn btn-danger">삭제</a>
       <div class="m-1"></div>
       <a class = "btn btn-primary" href = "{% url 'posts:add_comment_to_post' post.id %}">새댓글작성</a>
       <div class="m-1"></div>
       <table class = "table table-hover">
           <thead class = "thead-dark">
       <tr>
               <th scope = "col">#</th>
               <th scope = "col">제목</th>
               <th scope = "col">작성자</th>
               <th scope = "col">수정</th>
               <th scope = "col">삭제</th>

       </tr>
       <tbody>
               {% for comment in post.comment_set.all %}
               <tr>
                   <th scope = "row">{{ comment.id }}</th>
                   <td><a href="/posts/{{ comment.id }}/c_detail">{{ comment.contents_comment }}</a></td>
                   <td>{{ comment.author_comment }}</td>
                   <td>
                       <a href = "{% url 'posts:update_comment' comment.id %}" class = "btn btn-warning">수정</a>
                   </td>
                   <td>
                       <a href= "{% url 'posts:delete_comment' comment.id %}" class = "btn btn-danger">삭제</a>
                   </td>
               </tr>
               {% endfor %}
       </tbody>
       </div>

{% endblock %}